version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_app
        ports:
            - "8080:8000"
        volumes:
            - .:/var/www/html
        command: sh -c "cp .env.example .env && composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8000"
        environment:
            - VIRTUAL_HOST=localhost
            - VIRTUAL_PORT=8000
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
