version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        command: sh -c "cp .env.example .env && apache2-foreground" # Copia el .env antes de iniciar Apache
        environment:
            - VIRTUAL_HOST=localhost
            - VIRTUAL_PORT=80
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
